RPPP-WebApp/RPPP-WebApp/ViewModels/ProjectPartnerViewModel.cs
namespace RPPP_WebApp.ViewModels
{
    /// <summary>
    /// Represents a view model for displaying partnerships.
    /// </summary>
    public class ProjectPartnerViewModel
    {/// <summary>
     /// Gets or sets the unique identifier of the partnership.
     /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// Gets or sets the name of the Project entity associated with this partnership.
        /// </summary>
        public string Project { get; set; }
        /// <summary>
        /// Gets or sets the name of the worker associated with this partnership.
        /// </summary>
        public string Worker { get; set; }
        /// <summary>
        /// Gets or sets the name of the role associated with this partnership.
        /// </summary>
        public string Role { get; set; }
        /// <summary>
        /// Gets or sets the start date of the partnership.
        /// </summary>
        public DateTime DateFrom { get; set; }
        /// <summary>
        /// Gets or sets the end date of the partnership.
        /// </summary>
        public DateTime? DateTo { get; set; }
      
    }
}

RPPP-WebApp/RPPP-WebApp/ViewModels/ProjectPartnersViewModel.cs
using RPPP_WebApp.Model;

namespace RPPP_WebApp.ViewModels
{  /// <summary>
   /// Represents a view model for displaying partnerships with paging information and optional filtering.
   /// </summary>
    public class ProjectPartnersViewModel
    { /// <summary>
      /// Gets or sets the collection of partnerships.
      /// </summary>
        public IEnumerable<ProjectPartnerViewModel> Partners { get; set; }
        /// <summary>
        /// Gets or sets a new partnership.
        /// </summary>
        public ProjectPartner newPartner { get; set; }
        /// <summary>
        /// Gets or sets the paging information for the partnerships.
        /// </summary>
        public PagingInfo PagingInfo { get; set; }
        /// <summary>
        /// Gets or sets the filter criteria for partnerships.
        /// </summary>
        public ProjectPartnerFilter Filter { get; set; }
        /// <summary>
        /// Gets or sets the related Worker entity.
        /// </summary>
        public Worker worker { get; set; }

    }
}

RPPP-WebApp/RPPP-WebApp/Controllers/ProjectPartnerController.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using NLog.Filters;
using RPPP_WebApp.Extensions;
using RPPP_WebApp.Extensions.Selectors;
using RPPP_WebApp.Model;
using RPPP_WebApp.ViewModels;

namespace RPPP_WebApp.Controllers
{    /// <summary>
     /// Controller for managing partnerships.
     /// </summary>
    public class ProjectPartnerController : Controller
    {

        private readonly Rppp01Context ctx;
        private readonly ILogger<TransactionTypeController> logger;
        private readonly AppSettings appData;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectPartnerController"/> class.
        /// </summary>
        /// <param name="ctx">The database context.</param>
        /// <param name="options">Application settings.</param>
        /// <param name="logger">The logger.</param>
        /// <returns>A new instance of the <see cref="ProjectPartnerController"/> class.</returns>
        public ProjectPartnerController(Rppp01Context ctx, IOptionsSnapshot<AppSettings> options, ILogger<TransactionTypeController> logger)
        {
            this.ctx = ctx;
            this.logger = logger;
            appData = options.Value;
        }
        /// <summary>
        /// Displays a paginated list of partners.
        /// </summary>
        /// <param name="page">The page number.</param>
        /// <param name="sort">The sort option.</param>
        /// <param name="ascending">The sort direction.</param>
        /// <returns>The result of the action.</returns>
        public async Task <IActionResult> Index(ProjectPartnerFilter filter, int page = 1, int sort = 1, bool ascending = true)
        {
            var query = ctx.ProjectPartner
                           .AsNoTracking();
            int pagesize = appData.PageSize;

            string errorMessage = "Ne postoji niti jedan zapis";

            if (!string.IsNullOrEmpty(filter.Project))
            {
                query = query.Where(p => p.Project.Name.Contains(filter.Project));
                errorMessage += $" gdje je projekt: {filter.Project}";
            }
            if (!string.IsNullOrEmpty(filter.Worker))
            {
                query = query.Where(p => p.Worker.Email.Contains(filter.Worker));
                errorMessage += $" gdje je radnik: {filter.Worker}";
            }
            if (!string.IsNullOrEmpty(filter.Role))
            {
                query = query.Where(p => p.Role.Name.Contains(filter.Role));
                errorMessage += $" gdje je uloga: {filter.Role}";
            }

            int count = await query.CountAsync();
            if (count == 0)
            {
                logger.LogInformation(errorMessage);
                TempData[Constants.Message] = errorMessage;
                TempData[Constants.ErrorOccurred] = false;
                return RedirectToAction(nameof(Index));
            }


            var pagingInfo = new PagingInfo
            {
                CurrentPage = page,
                Sort = sort,
                Ascending = ascending,
                ItemsPerPage = pagesize,
                TotalItems = count
            };

            if (page < 1 || page > pagingInfo.TotalPages)
            {
                return RedirectToAction(nameof(Index), new { page = 1, sort, ascending });
            }


            query = query.ApplySort(sort, ascending);

            var partners = await query
            .Select(o => new ProjectPartnerViewModel
            {
                Id = o.Id,
                Project = o.Project.Name,
                Worker = $"{o.Worker.FirstName} {o.Worker.LastName}",
                Role = o.Role.Name,
                DateFrom = o.DateFrom,
                DateTo = o.DateTo
            })
            .Skip((page - 1) * pagesize)
            .Take(pagesize)
            .ToListAsync();

            var model = new ProjectPartnersViewModel
            {
                Partners = partners,
                PagingInfo = pagingInfo,
                Filter = filter
            };

            return View(model);
        }

        /// <summary>
        /// Displays the view for creating a new partnership.
        /// </summary>
        /// <returns>The result of the action.</returns>
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await PrepareDropDownLists();
            return View();
        }
        /// <summary>
        /// Handles the HTTP POST request for adding a new partnership.
        /// </summary>
        /// <param name="partner">The partnership data from the form.</param>
        /// <returns>Redirects to the partnership index on success; returns the form on failure.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectPartner partner)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    partner.Id = Guid.NewGuid();
                    ctx.Add(partner);
                    await ctx.SaveChangesAsync();

                    TempData[Constants.Message] = $"Suradnik je dodan na projekt.";
                    TempData[Constants.ErrorOccurred] = false;
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception exc)
                {
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    await PrepareDropDownLists();
                    return View(partner);
                }
            }
            else
            {
                await PrepareDropDownLists();
                return View(partner);
            }
        }
        /// <summary>
        /// Opens the form for editing data about an existing partnership.
        /// </summary>
        /// <param name="id">The unique identifier of the partnership to edit.</param>
        /// <param name="page">Current page number.</param>
        /// <param name="sort">Sort order.</param>
        /// <param name="ascending">Whether sorting is in ascending order.</param>
        /// <returns>Project partner edit view.</returns>
        public async Task<IActionResult> Edit(Guid id, int page = 1, int sort = 1, bool ascending = true)
        {
            var partner = ctx.ProjectPartner.AsNoTracking().Where(o => o.Id == id).SingleOrDefault();
            if (partner  == null)
            {
                logger.LogWarning("Ne postoji suradnik: " + id);
                return NotFound("Ne postoji suradnik: " + id);
            }
            else
            {
                ViewBag.Page = page;
                ViewBag.Sort = sort;
                ViewBag.Ascending = ascending;
                await PrepareDropDownLists();
                return View(partner);
            }
        }
        /// <summary>
        /// Handles the HTTP POST request for updating data about an existing partnership.
        /// </summary>
        /// <param name="id">The unique identifier of the organization to be updated.</param>
        /// <param name="page">The current page number.</param>
        /// <param name="sort">The sort order.</param>
        /// <param name="ascending">Whether the sorting is in ascending order.</param>
        /// <returns>Redirects to the index view if successful, otherwise returns the edit view with error messages.</returns>
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Guid id, int page = 1, int sort = 1, bool ascending = true)
        {
            try
            {
                ProjectPartner partner = await ctx.ProjectPartner
                                  .Where(o => o.Id == id)
                                  .FirstOrDefaultAsync();
                if (partner == null)
                {
                    return NotFound("Neispravan id suradnika: " + id);
                }

                if (await TryUpdateModelAsync(partner, "",
                    o => o.Id, o => o.ProjectId, o => o.WorkerId, o => o.RoleId, o => o.DateFrom, o => o.DateTo
                ))
                {
                    ViewBag.Page = page;
                    ViewBag.Sort = sort;
                    ViewBag.Ascending = ascending;
                    try
                    {
                        await ctx.SaveChangesAsync();
                        TempData[Constants.Message] = $"Suradnik je ažuriran.";
                        TempData[Constants.ErrorOccurred] = false;
                        return RedirectToAction(nameof(Index), new { page = page, sort = sort, ascending = ascending });
                    }
                    catch (Exception exc)
                    {
                        ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                        await PrepareDropDownLists();
                        return View(partner);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Podatke o suradniku nije moguće povezati s forme");
                    await PrepareDropDownLists();
                    return View(partner);
                }
            }
            catch (Exception exc)
            {
                TempData[Constants.Message] = exc.CompleteExceptionMessage();
                TempData[Constants.ErrorOccurred] = true;
                return RedirectToAction(nameof(Edit), new { id = id, page = page, sort = sort, ascending = ascending });
            }
        }
                 /// <summary>
                 /// Deletes a partnership with the specified id.
                 /// </summary>
                 /// <param name="Id">The unique identifier of the partnership to remove.</param>

RPPP-WebApp/RPPP-WebApp/Views/ProjectPartner/Create.cshtml
@model RPPP_WebApp.Model.ProjectPartner

@{
	ViewData["Title"] = "Novi suradnik";
}

<h2 class="mt-3">Unos novog suradnika</h2>

<form asp-action="Create" method="post">
  <div asp-validation-summary="All"></div>
    <div class="mt-3">
    <label asp-for="ProjectId" class="form-label">Ime projekta</label>
    <select class="form-control" asp-for="ProjectId" asp-items="ViewBag.Projects">
        <option disabled selected value="">Odaberite projekt</option>
    </select>
    <div class="form-text"><span asp-validation-for="ProjectId" class="text-danger"></span></div>
  </div>
   <div class="mt-3">
    <label asp-for="WorkerId" class="form-label">Ime radnika</label>
    <select class="form-control" asp-for="WorkerId" asp-items="ViewBag.Workers">
        <option disabled selected value="">Odaberite radnika</option>
    </select>
    <div class="form-text"><span asp-validation-for="WorkerId" class="text-danger"></span></div>
  </div>
   <div class="mt-3">
    <label asp-for="RoleId" class="form-label">Ime uloge</label>
    <select class="form-control" asp-for="RoleId" asp-items="ViewBag.ProjectRoles">
        <option disabled selected value="">Odaberite ulogu</option>
    </select>
    <div class="form-text"><span asp-validation-for="RoleId" class="text-danger"></span></div>
  </div>
      <div class="mt-3">
        <label asp-for="DateFrom" class="form-label">Angažiran od</label>
        <input asp-for="DateFrom" class="form-control" />
        <div class="form-text"><span asp-validation-for="DateFrom" class="text-danger"></span></div>
    </div>
        <div class="mt-3">
        <label asp-for="DateTo" class="form-label">Angažiran do</label>
        <input asp-for="DateTo" class="form-control" />
        <div class="form-text"><span asp-validation-for="DateTo" class="text-danger"></span></div>
    </div>
  <div class="text-center mt-3">
    <button class="btn btn-primary" type="submit">Dodaj</button>
    <a asp-action="Index" class="btn btn-secondary">Odustani</a>
  </div>
</form>

@section scripts {
  <partial name="IncludeValidation" />
}

RPPP-WebApp/RPPP-WebApp/Views/ProjectPartner/Edit.cshtml
@model RPPP_WebApp.Model.ProjectPartner

@{
    ViewData["Title"] = "Ažuriraj suradnika";
}

<form asp-route-id="@Model.Id"
      asp-route-page="@ViewBag.Page"
      asp-route-sort="@ViewBag.Sort"
      asp-route-ascending="@ViewBag.Ascending"
      method="post">
    <div asp-validation-summary="All"></div>
    <div class="form-group mt-3">
    <label asp-for="ProjectId" class="form-label">Projekt</label>
    <select class="form-control" asp-for="ProjectId" asp-items="ViewBag.Projects">
      <option disabled selected value="">Odaberite projekt</option>
    </select>
    <div class="form-text"><span asp-validation-for="ProjectId" class="text-danger"></span></div>
  </div>
      <div class="form-group mt-3">
    <label asp-for="WorkerId" class="form-label">Radnik</label>
    <select class="form-control" asp-for="WorkerId" asp-items="ViewBag.Workers">
      <option disabled selected value="">Odaberite radnika</option>
    </select>
    <div class="form-text"><span asp-validation-for="WorkerId" class="text-danger"></span></div>
  </div>
      <div class="form-group mt-3">
    <label asp-for="RoleId" class="form-label">Uloga</label>
    <select class="form-control" asp-for="RoleId" asp-items="ViewBag.ProjectRoles">
      <option disabled selected value="">Odaberite ulogu</option>
    </select>
    <div class="form-text"><span asp-validation-for="RoleId" class="text-danger"></span></div>
  </div>
        <div class="mt-3">
        <label asp-for="DateFrom" class="form-label">Angažiran od</label>
        <input asp-for="DateFrom" class="form-control" />
        <div class="form-text"><span asp-validation-for="DateFrom" class="text-danger"></span></div>
    </div>
        <div class="mt-3">
        <label asp-for="DateTo" class="form-label">Angažiran do</label>
        <input asp-for="DateTo" class="form-control" />
        <div class="form-text"><span asp-validation-for="DateTo" class="text-danger"></span></div>
    </div>
    <div class="text-center mt-3">
        <button class="btn btn-primary" type="submit">Spremi</button>
        <a asp-action="Index"
           asp-route-page="@ViewBag.Page"
           asp-route-sort="@ViewBag.Sort"
           asp-route-ascending="@ViewBag.Ascending"
           class="btn btn-secondary">Odustani</a>
    </div>
</form>

@section scripts {
    <partial name="IncludeValidation" />
}

RPPP-WebApp/RPPP-WebApp/Views/ProjectPartner/Filter.cshtml
@model RPPP_WebApp.ViewModels.ProjectPartnerFilter

<form asp-action="Index" asp-controller="ProjectPartner" method="get">
  <div class="form-group">
    <label asp-for="Project">Filtriraj po <strong>projektu</strong>:</label>
    <input asp-for="Project" class="form-control" />
  </div>
  <div class="form-group">
    <label asp-for="Worker">Filtriraj po <strong>radniku</strong>:</label>
    <input asp-for="Worker" class="form-control" />
  </div>
  <div class="form-group">
    <label asp-for="Role">Filtriraj po <strong>ulozi</strong>:</label>
    <input asp-for="Role" class="form-control" />
  </div>
  <div class="mt-3">
    <button type="submit" class="btn btn-primary">Filtriraj</button>
    <a asp-action="Index" asp-controller="ProjectPartner" class="btn btn-secondary">Očisti filter</a>
  </div>
</form>

RPPP-WebApp/RPPP-WebApp/Views/ProjectPartner/Index.cshtml
@using RPPP_WebApp

@model RPPP_WebApp.ViewModels.ProjectPartnersViewModel

@{
    ViewData["Title"] = "Suradnici na projektu";
}

<h1 class="mt-3">Suradnici</h1>

<a asp-action="Create">Unos novog suradnika</a>

<partial name="Filter" model="Model.Filter" />

<pager page-info="@Model.PagingInfo" page-action="Index" page-title="Unesite željenu stranicu" class="float-end"></pager>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                <a asp-route-sort="1" asp-route-page="@Model.PagingInfo.CurrentPage" asp-route-ascending="@(Model.PagingInfo.Sort == 1 ? !Model.PagingInfo.Ascending : true)">
                    Suradnik
                </a>
            </th>
            <th>
                <a asp-route-sort="2" asp-route-page="@Model.PagingInfo.CurrentPage" asp-route-ascending="@(Model.PagingInfo.Sort == 2 ? !Model.PagingInfo.Ascending : true)">
                    Projekt
                </a>
            </th>
            <th>
                <a asp-route-sort="3" asp-route-page="@Model.PagingInfo.CurrentPage" asp-route-ascending="@(Model.PagingInfo.Sort == 3 ? !Model.PagingInfo.Ascending : true)">
                    Uloga
                </a>
            </th>
             <th>
                <a asp-route-sort="4" asp-route-page="@Model.PagingInfo.CurrentPage" asp-route-ascending="@(Model.PagingInfo.Sort == 4 ? !Model.PagingInfo.Ascending : true)">
                    Od
                </a>
            </th>
            <th>
                <a asp-route-sort="5" asp-route-page="@Model.PagingInfo.CurrentPage" asp-route-ascending="@(Model.PagingInfo.Sort == 5 ? !Model.PagingInfo.Ascending : true)">
                    Do
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var partner in Model.Partners)
        {
            <tr>

                
                <td class="text-left">@partner.Worker</td>
                <td class="text-left">@partner.Project</td>
                <td class="text-left">@partner.Role</td>
                <td class="text-left">@partner.DateFrom</td>
                <td class="text-left">@partner.DateTo</td>
                <td class="btn-toolbar gap-2 justify-content-end">
                    <a asp-action="Edit"
                       asp-route-id="@partner.Id"
                       asp-route-page="@Model.PagingInfo.CurrentPage"
                       asp-route-sort="@Model.PagingInfo.Sort"
                       asp-route-ascending="@Model.PagingInfo.Ascending"
                       class="btn btn-sm btn-success" title="Ažuriraj">Edit</a>
                    <form asp-action="Delete" method="post"
                          asp-route-page="@Model.PagingInfo.CurrentPage"
                          asp-route-sort="@Model.PagingInfo.Sort"
                          asp-route-ascending="@Model.PagingInfo.Ascending">
                        <input type="hidden" name="Id" value="@partner.Id" />
                        <button type="submit" class="btn btn-sm btn-danger delete" title="Obriši">Delete</button>
                    </form>
                </td>

            </tr>
        }

    </tbody>
</table>

@section scripts {
    <script src="~/js/pager.js" asp-append-version="true"></script>
    <script src="~/lib/htmx/htmx.min.js" asp-append-version="true"></script>
    <partial name="IncludeValidation" />

    <script>
        document.body.addEventListener("showMessage", function (evt) {
            toastr[evt.detail.messageType](evt.detail.message);
        })
        document.body.addEventListener("htmx:responseError", function (evt) {
            toastr["error"](evt.detail.error);
        })
    </script>
}